theme: jekyll-theme-leap-day
title: [Python Crash Course]
description: [o'zbek tilidagi tarjimasi]

github:
  martianvenusian_url: https://martianvenusian.github.io
  repository_name: [Python Crash Course]
